package name.qd.analysis.chip;

public enum ChipAnalyzers {
	BIG_VOLUME_TRADE,
	DAILY_PNL,
	TOTAL_PNL,
	DAILY_TRADE_RECORD,
	DAILY_OPEN,
	DAILY_OPEN_M_CLOSE,
	BACK_TEST_PATTERN_1,
	BRANCH_INFO_BY_BS,
	BRANCH_INFO_BY_CACHE,
	BEST_BRANCH_BUY_SELL,
	;
}
